### ISSUE TITLE
Unable to connect to the server container from the host client 

### ISSUE THREAD

**Issue by MaurizioSodano** [MaurizioSodano/java.RMI.Docker#1]
It works as expected when running on two containers (server and client) running on the same host.

<pre><code>
15:49:11.277 [main] INFO com.javacodegeeks.core.rmi.remoteclient.RemoteClient - Locating Registry: remoteHost:RMI_SERVER port:8888
15:49:11.301 [main] INFO com.javacodegeeks.core.rmi.remoteclient.RemoteClient - Lookup Interface: remoteID:RMI_EXAMPLE
15:49:11.457 [main] INFO com.javacodegeeks.core.rmi.remoteclient.RemoteClient - RMI returns:JAVACODEGEEKS ROCK!
</code></pre>

 
It fails when running the server from the docker container and the client from the host machine trying to connect to the server.

<pre><code>
17:02:10.928 [main] INFO com.javacodegeeks.core.rmi.remoteclient.RemoteClient - Locating Registry: remoteHost:localhost port:8888
17:02:11.468 [main] INFO com.javacodegeeks.core.rmi.remoteclient.RemoteClient - Lookup Interface: remoteID:RMI_EXAMPLE
17:02:53.564 [main] ERROR com.javacodegeeks.core.rmi.remoteclient.RemoteClient - Connection refused to host: 192.168.32.2; nested exception is: 
	java.net.ConnectException: Connection timed out: connect
java.rmi.ConnectException: Connection refused to host: 192.168.32.2; nested exception is: 
	java.net.ConnectException: Connection timed out: connect
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
	at com.sun.proxy.$Proxy0.capitalize(Unknown Source)
	at com.javacodegeeks.core.rmi.remoteclient.RemoteClient.main(RemoteClient.java:28)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 7 common frames omitted
</code></pre>

**Comment by eduyayo** [comment]
I've got the very same error even when running in two containers...

**Comment by eduyayo** [comment]
I've found that changing the network_mode to host in the server container and adding the naming -Djava.rmi.server.hostname=192.168.99.100 in the server start script allows me to connect from the host machine. I've stiched this stuff together from several sites so I can't remember the references but those two changes allow to connect.

**Comment by MaurizioSodano** [comment]
Hi @eduyayo, many thanks for digging into this issue.
I've created a new branch bugfix/clientLocalConnection implementing your suggestions.
Just to be sure to have done it properly, I summarize the steps here:
 1.  added network_mode: host in the docker-compose.yml
 2. added -Djava.rmi.server.hostname=192.168.99.100* in the server start script
 3. recompiled all (mvn clean install)
 4. launch the server in docker (docker-compose up -d RMI_SERVER)

And here I have my problem starting the container :
--->Error: Unable to access jarfile rmiServer-0.0.1-SNAPSHOT.jar


*I have a doubt if I should put here the IP of my docker container

**Comment by eduyayo** [comment]
mh... I've checked out the branch, I've decompressed the tar file and the jar is inside a folder called maven. Any changes in the build process from the master to the fix?!

**Comment by eduyayo** [comment]
not the best plugin for building the image... it seems to be having repeated entries or something... have you tried this one? <groupId>com.google.cloud.tools</groupId>
<artifactId>jib-maven-plugin</artifactId>
<version>1.8.0</version>

**Comment by MaurizioSodano** [comment]
Thanks again @eduyayo. 
I'll look into this plugin and check if it works.

**Comment by bsorrentino** [comment]
@MaurizioSodano did have you taken a look [here](https://stackoverflow.com/questions/43759967/java-rmi-server-in-docker-container)?

**Comment by MaurizioSodano** [comment]
Hi @eduyayo,
I've used jib plugin instead of fabric8 in branch https://github.com/MaurizioSodano/java.RMI.Docker/tree/bugfix/clientLocal

Using these configuration in docker-compose.yml

```
version: '3.3'

services:
  RMI_SERVER:
    container_name: RMI_SERVER
    image: rmiserver:latest
    network_mode: host
    ports:
      - '8888:8888'
    environment:
      - "JAVA_OPTS=-Djava.rmi.server.hostname=192.168.99.100 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=8888 -Dcom.sun.management.jmxremote.rmi.port=8888 -Dcom.sun.management.jmxremote.ssl=false"

  RMI_CLIENT:
    container_name: RMI_CLIENT
    image: rmiclient:latest
    environment:
      REMOTE_HOST: RMI_SERVER
    depends_on:
      - RMI_SERVER
    links:
      - RMI_SERVER
```


It doesn't work even  in docker containers 

> docker-compose up -d

> docker-compose logs -f

```
Attaching to RMI_CLIENT, RMI_SERVER
RMI_CLIENT    | 2020-05-06 08:04:12,966 [main] INFO  c.j.c.r.r.RemoteClient - Locating Registry: remoteHost:RMI_SERVER port:8888
RMI_CLIENT    | 2020-05-06 08:04:12,982 [main] INFO  c.j.c.r.r.RemoteClient - Lookup Interface: remoteID:RMI_EXAMPLE
RMI_CLIENT    | 2020-05-06 08:04:14,694 [main] ERROR c.j.c.r.r.RemoteClient - Unknown host: RMI_SERVER; nested exception is:
RMI_CLIENT    |         java.net.UnknownHostException: RMI_SERVER
RMI_CLIENT    | java.rmi.UnknownHostException: Unknown host: RMI_SERVER; nested exception is:
RMI_CLIENT    |         java.net.UnknownHostException: RMI_SERVER
RMI_CLIENT    |         at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:616)
RMI_CLIENT    |         at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
RMI_CLIENT    |         at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
RMI_CLIENT    |         at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
RMI_CLIENT    |         at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
RMI_CLIENT    |         at com.javacodegeeks.core.rmi.remoteclient.RemoteClient.main(RemoteClient.java:26)
RMI_CLIENT    | Caused by: java.net.UnknownHostException: RMI_SERVER
RMI_CLIENT    |         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
RMI_CLIENT    |         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
RMI_CLIENT    |         at java.net.Socket.connect(Socket.java:589)
RMI_CLIENT    |         at java.net.Socket.connect(Socket.java:538)
RMI_CLIENT    |         at java.net.Socket.<init>(Socket.java:434)
RMI_CLIENT    |         at java.net.Socket.<init>(Socket.java:211)
RMI_CLIENT    |         at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
RMI_CLIENT    |         at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
RMI_CLIENT    |         at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
RMI_CLIENT    |         ... 5 common frames omitted
RMI_SERVER    | 2020-05-06 08:04:11,344 [main] INFO  c.j.c.r.r.RemoteServer - Binded  id:RMI_EXAMPLE port:8888
RMI_CLIENT exited with code 0
```

**Comment by MaurizioSodano** [comment]
> @MaurizioSodano did have you taken a look [here](https://stackoverflow.com/questions/43759967/java-rmi-server-in-docker-container)?

Hi @bsorrentino, I've implemented the suggested stackOverlow solution in branch https://github.com/MaurizioSodano/java.RMI.Docker/tree/bugfix/rmiServerDocker, but it gives the same error when connecting from the host

```
2020-05-06 15:04:18,367 [main] INFO  c.j.c.r.r.RemoteClient - Locating Registry: remoteHost:172.18.35.81 port:8888
2020-05-06 15:04:18,972 [main] INFO  c.j.c.r.r.RemoteClient - Lookup Interface: remoteID:RMI_EXAMPLE
2020-05-06 15:05:01,087 [main] ERROR c.j.c.r.r.RemoteClient - Connection refused to host: 172.19.0.2; nested exception is: 
	java.net.ConnectException: Connection timed out: connect
java.rmi.ConnectException: Connection refused to host: 172.19.0.2; nested exception is: 
	java.net.ConnectException: Connection timed out: connect
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
	at com.sun.proxy.$Proxy2.capitalize(Unknown Source)
	at com.javacodegeeks.core.rmi.remoteclient.RemoteClient.main(RemoteClient.java:29)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 7 common frames omitted

Process finished with exit code 0

```

**Comment by eduyayo** [comment]
Hi, I've done some tests and found out that the client is running far too fast for the server to be up and ready. If you just run the whole thing, you've got that error but...
If you stop the client with docker stop RMI_CLIENT and start it again with docker start, you get a succesful connection. It is done, you've done well!! but the client runs too fast.

Dirty solutions:
- add some sysout in the server and test for it to appear with cat|grep or something for it to be done starting
- or add a Thread.sleep in the client before looking for the register
- add some util in the client waiting for the port to be open/available similar to this: https://stackoverflow.com/a/17657377/1180963

and my preferred:
cycle the client until connected with a cooldown timer. Sorry I don't have your java version currently so am writting pseudocode:
```
connected = false;
while (!connected) {
try {
connect();
connected = true;
} catch (any) {
coolDownTimeWait();
}
}
```

**Comment by eduyayo** [comment]
btw... I've added this to the server code:
	
		```
while (true) {
			Thread.sleep(3000L);
			System.out.println("server alive...");
		}
```
So it never dies...

**Comment by bsorrentino** [comment]
Hi all

I've inspected connection hands-shaking between client and server and I've seen that the server return to the client a random port number plus its address that, in the case of docker, it is the internal container address not accessible from outside to docker VM

**Comment by eduyayo** [comment]
Forget it, it works. It happens not to be synchronized. 

That "random port" is an ephemeral https://en.wikipedia.org/wiki/Ephemeral_port usted as a socket for serving the client.
